apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: test
subjects:
- kind: ServiceAccount
  name: peter
  namespace: test
roleRef:
  kind: Role
  name: service-role
  apiGroup: rbac.authorization.k8s.io

